/// Flutter icons CustumIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustumIcons
///      fonts:
///       - asset: fonts/CustumIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustumIcons {
  CustumIcons._();

  static const _kFontFam = 'CustumIcons';
  static const String? _kFontPkg = null;

  static const IconData mail = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spam = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firewall = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData antivirus = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bypassing = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spyware = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
